name: C/C++ CI

on: [push]

jobs:
  build:
    name: Build on node ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, windows-latest, macOS-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: install_deps
      if: matrix.os == 'ubuntu-16.04'
      run: ./build_files/build_environment/install_deps.sh --no-confirm --build-all
    - name: make
      if: matrix.os == 'ubuntu-16.04'
      run: make -f GNUmakefile
